# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7dc9f0a33de5a485db43b3795eed19927f620ffa8dc076bac21036f0e046032292142961b7ad7256807ddae83af789411af78c9a33b9638dfc5d14a586dd6a

test:
  secret_key_base: 1042273861ee7067d8a2ef5ab83df4fc329e9856ff9b2e5874b863be36b6549e0fcdca9df89855bb2f49de449ea47344a4c4a559877e0f8b5123225ff93f2d15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
